#!/bin/bash

TMUX=my_tmux

read -r -d '' w1_env <<-EOF
    echo "To exit from the tmux session type Ctrl-b d"
    /bin/bash
EOF


tmux new-session -d -s $TMUX -n W1 bash -c "$w1_env"
tmux new-window -t $TMUX -n W2
tmux new-window -t $TMUX -n W3
tmux new-window -t $TMUX -n W4
tmux new-window -t $TMUX -n W5

tmux select-window -t $TMUX:W1
tmux set-option -g mouse on
tmux attach -t $TMUX
