#!/bin/bash
# Use the Ubuntu 24.04 base image
#FROM ubuntu:22.04
# Update package lists
echo "apt-get -y update"
DEBIAN_FRONTEND=noninteractive apt-get -y update

echo "apt-get -y upgrade"
DEBIAN_FRONTEND=noninteractive apt-get -y upgrade

echo "apt-get install -y gcc"
DEBIAN_FRONTEND=noninteractive apt-get install -y gcc

echo "apt-get install -y wget"
DEBIAN_FRONTEND=noninteractive apt-get install -y wget

echo "apt-get install -y linux-headers-$(uname -r)"
DEBIAN_FRONTEND=noninteractive apt-get install -y linux-headers-$(uname -r)

echo "wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb"
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb

echo "dpkg -i cuda-keyring_1.1-1_all.deb"
dpkg -i cuda-keyring_1.1-1_all.deb

echo "apt-get update"
apt-get update

echo "apt-get install -y cuda-toolkit"
DEBIAN_FRONTEND=noninteractive apt-get install -y cuda-toolkit

#install the legacy kernel module flavor:
#echo "apt-get install -y cuda-drivers"
#DEBIAN_FRONTEND=noninteractive apt-get install -y cuda-drivers

#install the open kernel module flavor:
echo "apt-get install -y nvidia-driver-555-open"
DEBIAN_FRONTEND=noninteractive apt-get install -y nvidia-driver-555-open

echo "apt-get install -y cuda-drivers-555"
DEBIAN_FRONTEND=noninteractive apt-get install -y cuda-drivers-555
