#!/bin/bash

# Update package lists
echo "apt-get -y update"
DEBIAN_FRONTEND=noninteractive apt-get -y update

echo "apt-get -y upgrade"
DEBIAN_FRONTEND=noninteractive apt-get -y upgrade

echo "apt-get install -y gcc"
DEBIAN_FRONTEND=noninteractive apt-get install -y gcc

echo "apt-get install -y wget"
DEBIAN_FRONTEND=noninteractive apt-get install -y wget

# needed for the creation of nccl package
echo "apt install build-essential devscripts debhelper fakeroot"
DEBIAN_FRONTEND=noninteractive apt install -y build-essential devscripts debhelper fakeroot

echo "apt-get install -y linux-headers-$(uname -r)"
DEBIAN_FRONTEND=noninteractive apt-get install -y linux-headers-$(uname -r)

echo "wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb"
wget -O cuda-keyring_1.1-1_all.deb  https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb

echo "dpkg -i cuda-keyring_1.1-1_all.deb"
dpkg -i cuda-keyring_1.1-1_all.deb

echo "apt-get update"
apt-get update

echo "apt-get install -y cuda-toolkit"
DEBIAN_FRONTEND=noninteractive apt-get install -y cuda-toolkit

#install the legacy kernel module flavor:
#echo "apt-get install -y cuda-drivers"
#DEBIAN_FRONTEND=noninteractive apt-get install -y cuda-drivers

#install the open kernel module flavor:
echo "apt-get install -y nvidia-driver-555-open"
DEBIAN_FRONTEND=noninteractive apt-get install -y nvidia-driver-555-open

echo "apt-get install -y cuda-drivers-555"
DEBIAN_FRONTEND=noninteractive apt-get install -y cuda-drivers-555

# post installation 
echo "adduser mpi"

adduser --quiet --disabled-password --gecos "" mpi && \
	{ echo "mpi:mpi" | chpasswd && adduser mpi sudo; } || true

#assuming that ./Scriptfile is run in the same folder of the local git repository
echo "cp debug_trace.sh /home/mpi"
cp debug_trace.sh /home/mpi

echo "setup cuda PATH and LD_LIBRARY PATH for root and mpi users"

echo "export PATH=/usr/local/cuda/bin\${PATH:+:\${PATH}}" >> /root/.bashrc
echo "export LD_LIBRARY_PATH=/usr/local/cuda-12.2/lib64\${LD_LIBRARY_PATH:+:\${LD_LIBRARY_PATH}}" >> /root/.bashrc

echo "export PATH=/usr/local/cuda/bin\${PATH:+:\${PATH}}" >> /home/mpi/.bashrc
echo "export LD_LIBRARY_PATH=/usr/local/cuda-12.2/lib64\${LD_LIBRARY_PATH:+:\${LD_LIBRARY_PATH}}" >> /home/mpi/.bashrc

echo "setup mpi LD_LIBRARY PATH mpi user"
echo "export LD_LIBRARY_PATH=/usr/local/lib\${LD_LIBRARY_PATH:+:\${LD_LIBRARY_PATH}}" >> /home/mpi/.bashrc

# GDS (GPUDirect Storage) install is disabled at the moment
#apt-get install nvidia-gds
